### PR TITLE
Resync xkcd-webserver with the store version and bump version to 16.04-3

### PR DESCRIPTION
**Pull request by didrocks**

### CODE REVIEW

**Comment by zyga** [comment]
+1

**Comment by didrocks** [comment]
@zyga: seems you didn't push the merge button yet ;) I just had to reupload another version with a manual mksquashfs (see on IRC the discussion with jdstrand). Seems snappy build doesn't use the correct parameters for now. I'll file a bug and fix it tomorrow.

Meanwhile, there is a new veresion of xkcd-webserver ready in the store, mind merging this branch to be in sync with the store?

**Comment by zyga** [comment]
@didrocks I'm sorry but I don't have write access here.

**Comment by didrocks** [comment]
No worry, anyone reading this having write access?

**Pull request merged**
